version: '3.8'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: utilal/foodgram_backend
    volumes:
      - static:/static
      - media:/media
    env_file: .env
  frontend:
    env_file: .env
    image: utilal/foodgram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: utilal/foodgram_gateway
    env_file: .env
    ports:
      - 7000:80
    volumes:
      - static:/static
      - media:/media

